services:
  db:
    image: postgres:13
    restart: always
    container_name: prisma-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: boggle
    ports:
      - '5432:5432'
    networks:
      - app-network

  app:
    build: .
    container_name: boggle
    ports:
      - '80:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
